### ISSUE TITLE
GitHub actions only works for master branch

### ISSUE THREAD

**Issue by pava-14** [pava-14/aqa1.1#3]
# GitHub actions only works for master branch

***

***Steps:***

1. Create gradle.yml:
```
name: Java CI with Gradle
on:
  push:
    branches: [ master, testng, junit4 ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
```
2. Push to branch testing

***Actual result:***
Wokflow "Java CI with Gradle" not started.

***Expected result***
Wokflow "Java CI with Gradle" started.

***Screnshot***
![OnlyMasterBranch](https://user-images.githubusercontent.com/63086116/86079057-bb298d00-bab9-11ea-9813-9b618cb790a2.png)
